M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-11-06T16:29:17+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-06T16:29:17+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
%
G90
G05
T1
G00X8.5666Y-2.8299
M15
G01X8.6Y-2.7965
M16
G05
M30
